
#version 460 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
	
struct LightData
{
    vec4 position;
    vec4 color;
    vec4 attenuation;
    vec4 spotDirection;
};

layout(std430) buffer LightDataBuffer
{
    LightData lightDataBuffer[];
};

void main() 
{
    for (int i = 0; i < lightDataBuffer.length(); ++i)
    {
        lightDataBuffer[lightIndex].position = vec4(0.1);
    }
}
